# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-camcalibration-dep
  labels:
    app: {{ .Release.Name }}-camcalibration
  annotations:
    container.apparmor.security.beta.kubernetes.io/camcalibration: unconfined
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-camcalibration
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-camcalibration
    spec:
      shareProcessNamespace: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        supplementalGroups: [4000]
      initContainers:
        - name: wait-for-web-initcontainer
          image: busybox
          securityContext:
            readOnlyRootFilesystem: true
          command: ["/bin/sh", "-c", "until wget -q --spider http://web.{{ .Release.Namespace }}.svc.cluster.local; do sleep 1; done"]
      containers:
        - args:
          - camcalibration
          - --broker
          - broker.{{ .Release.Namespace }}.svc.cluster.local
          - --resturl
          - https://web.{{ .Release.Namespace }}.svc.cluster.local/api/v1
          image: {{ .Values.repository }}/{{ .Values.camcalibration.image }}:{{ .Chart.AppVersion }}
          name: {{ .Release.Name }}-camcalibration
          env:
          - name: EGL_PLATFORM
            value: surfaceless
{{- if .Values.proxy.enabled }}
          - name: HTTP_PROXY
            value: {{ .Values.proxy.httpProxy }}
          - name: HTTPS_PROXY
            value: {{ .Values.proxy.httpsProxy }}
          - name: NO_PROXY
            value: {{ .Values.proxy.noProxy }}
          - name: http_proxy
            value: {{ .Values.proxy.httpProxy }}
          - name: https_proxy
            value: {{ .Values.proxy.httpsProxy }}
          - name: no_proxy
            value: {{ .Values.proxy.noProxy }}
{{- end }}
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            periodSeconds: 1
          resources: {}
          volumeMounts:
          - mountPath: /dev/fuse
            name: dev-fuse
          - mountPath: /run/secrets/certs
            name: certs
            readOnly: true
          - mountPath: /run/secrets/django
            name: django
            readOnly: true
          - mountPath: /run/secrets/calibration.auth
            name: calibration-auth
            readOnly: true
            subPath: calibration.auth
          - mountPath: /workspace/media
            name: media-storage
          - mountPath: /workspace/datasets
            name: datasets-storage
          - mountPath: /tmp
            name: tmp-dir
          - mountPath: /usr/local/lib/python3.10/dist-packages/third_party/netvlad
            name: netvlad-storage
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: dev-fuse
        hostPath:
          path: /dev/fuse
      - name: certs
        secret:
          secretName: {{ .Release.Name }}-certs
      - name: django
        secret:
          secretName: {{ .Release.Name }}-django
      - name: calibration-auth
        secret:
          secretName: {{ .Release.Name }}-calibration.auth
      - name: media-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-media-pvc
      - name: datasets-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-datasets-pvc
      - name: tmp-dir
        emptyDir:
          medium: Memory
      - name: netvlad-storage
        emptyDir:
          medium: Memory
status: {}
