# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ntp-dep
  labels:
    app: {{ .Release.Name }}-ntpserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ntpserv
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ntpserv
    spec:
      shareProcessNamespace: true
      securityContext:
        runAsUser: chrony
        runAsGroup: chrony
      initContainers:
        - command:
          - sh
          - -c
          - touch /tmp/healthy
          image: busybox
          name: init-healthy-file
          securityContext:
            readOnlyRootFilesystem : true
          volumeMounts:
          - name: healthy-file
            mountPath: /tmp
        # - command:
        #   - sh
        #   - -c
        #   - "chown -R chrony:chrony /etc/chrony && chown -R chrony:chrony /run/chrony && chown -R chrony:chrony /var/lib/chrony"
        #   image: busybox
        #   name: init-chrony-permissions
        #   securityContext:
        #     capabilities:
        #       add:
        #         - CHOWN
        #   volumeMounts:
        #   - name: etc-chrony
        #     mountPath: /etc/chrony
        #     readonly: false
        #   - name: run-chrony
        #     mountPath: /run/chrony
        #     readonly: false
        #   - name: var-lib-chrony
        #     mountPath: /var/lib/chrony
        #     readonly: false
      containers:
        - image: cturra/ntp
          name: {{ .Release.Name }}-ntpserv
          env:
          - name: NTP_SERVERS
            value: {{ .Values.ntpserv.ntpServers }}
{{- if .Values.proxy.enabled }}
          - name: HTTP_PROXY
            value: {{ .Values.proxy.httpProxy }}
          - name: HTTPS_PROXY
            value: {{ .Values.proxy.httpsProxy }}
          - name: NO_PROXY
            value: {{ .Values.proxy.noProxy }}
          - name: http_proxy
            value: {{ .Values.proxy.httpProxy }}
          - name: https_proxy
            value: {{ .Values.proxy.httpsProxy }}
          - name: no_proxy
            value: {{ .Values.proxy.noProxy }}
{{- end }}
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - CHOWN
            readOnlyRootFilesystem : true
          ports:
          - containerPort: 123
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            periodSeconds: 1
          volumeMounts:
          - name: healthy-file
            mountPath: /tmp
          - name: etc-chrony
            mountPath: /etc/chrony
            readonly: false
          - name: run-chrony
            mountPath: /run/chrony
            readonly: false
          - name: var-lib-chrony
            mountPath: /var/lib/chrony
            readonly: false
          resources: {}
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: healthy-file
        emptyDir: {}
      - name: etc-chrony
        emptyDir:
          medium: Memory
      - name: run-chrony
        emptyDir:
          medium: Memory
      - name: var-lib-chrony
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: ntpserv
spec:
  selector:
    app: {{ .Release.Name }}-ntpserv
  ports:
    - protocol: UDP
      port: 123
      targetPort: 123
