---
# SPDX-FileCopyrightText: (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "GitHub Actions"
    groups:
      github-actions-dependency:
        applies-to: version-updates
        patterns:
          - "*"
    reviewers:
      - "saratpoluri"
      - "dmytroye"
      - "tdorauintc"

  # Enable version updates for Helm charts
  - package-ecosystem: "helm"
    directory: "/kubernetes/scenescape-chart"
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Helm charts"
    groups:
      helm-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    reviewers:
      - "saratpoluri"
      - "dmytroye"
      - "tdorauintc"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/analytics"
      - "/autocalibration"
      - "/cluster_analytics"
      - "/controller"
      - "/kubernetes/init-images"
      - "/manager"
      - "/mapping"
      - "/scene_common"
      - "/tests/security/fuzzing"
      - "/tools/v2x"
      - "/tracker"
      - "/tracker/test/load"
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Dockerfile"
    groups:
      docker-images:
        applies-to: version-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: "python"
        update-types:
          [
            "version-update:semver-major",
            "version-update:semver-minor",
            "version-update:semver-patch",
          ]
    reviewers:
      - "saratpoluri"
      - "dmytroye"
      - "tdorauintc"

  # Enable version updates for Docker Compose
  - package-ecosystem: "docker-compose"
    directories:
      - "/cluster_analytics/tests/service"
      - "/sample_data/compose"
      - "/sample_data/demo_scenes/Queuing"
      - "/sample_data/demo_scenes/Retail"
      - "/sample_data/lidar_intersection"
      - "/tests/compose"
      - "/tests/compose/dlstreamer"
      - "/tests/compose/hierarchy"
      - "/tests/compose/perf"
      - "/tests/perf_tests/compose"
      - "/tests/security/libraries"
      - "/tools/pipeline_runner"
      - "/tools/px4_sih_demo"
      - "/tracker/test/load"
      - "/tracker/test/service"
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Docker Compose"
    groups:
      docker-compose-images:
        applies-to: version-updates
        patterns:
          - "*"
    reviewers:
      - "saratpoluri"
      - "dmytroye"
      - "tdorauintc"

  # Enable version updates for Python pip
  - package-ecosystem: "pip"
    directories:
      - "/.github/resources"
      - "/analytics"
      - "/autocalibration"
      - "/autocalibration/tools"
      - "/cluster_analytics"
      - "/cluster_analytics/tests/service"
      - "/cluster_analytics/tools/webui"
      - "/controller"
      - "/controller/src/robot_vision"
      - "/manager"
      - "/manager/test"
      - "/mapping"
      - "/mapping/tests"
      - "/scene_common"
      - "/tests"
      - "/tests/pipeline_runner"
      - "/tools/external_source_adapters"
      - "/tools/pipeline_runner"
      - "/tools/tracker/evaluation"
      - "/tools/upload_scenes"
      - "/tools/v2x"
      - "/tracker/test/load"
      - "/tracker/test/service"
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "pip"
    groups:
      python-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: "numpy"
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "Django"
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
    reviewers:
      - "saratpoluri"
      - "dmytroye"
      - "tdorauintc"

  # Enable version updates for NPM packages used in CI
  - package-ecosystem: "npm"
    directory: "/.github/resources"
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "npm"
    groups:
      npm-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    reviewers:
      - "Irakus"
      - "saratpoluri"
      - "dmytroye"
      - "tdorauintc"
