---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.
# See the LICENSE file in the root of this repository for details.

name: "Lint code"

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions:
  contents: read          # needed for actions/checkout

jobs:
  filter:
   name: "Lint code"
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        persist-credentials: false
    - name: Setup environment
      uses: open-edge-platform/orch-ci/.github/actions/bootstrap@d475e84f8b0b7bff118f0e8f56712390ef8d2828   # 0.1.26
      with:
        bootstrap_tools: "base,python,shellcheck,hadolint,"
    - name: Install python linters
      run: |
        pip install -r .github/resources/requirements.txt
    - name: Install Javascript linter
      run: |
        npm install --save-dev eslint@latest @eslint/js@latest
    - name: Install cpp linter
      run: |
        pipx install cpplint
    - name: Install HTML linter
      run: |
        npm install htmlhint --save-dev -g
    - name: Run Python linter - pylint
      if: always()
      run: |
        make lint-python-pylint
    - name: Run Python linter - flake8
      if: always()
      run: |
        make lint-python-flake8
    - name: Run JavaScript linter
      if: always()
      run: |
        make lint-javascript
    - name: Run C++ linter
      if: always()
      run: |
        make lint-cpp
    - name: Run shell linter - shellcheck
      if: always()
      run: |
        make lint-shell
    - name: Run HTML linter
      if: always()
      run: |
        make lint-html
    - name: Run dockerfiles linter
      if: always()
      run: |
        make lint-dockerfiles
    - name: Run prettier check
      if: always()
      run: |
        make prettier-check
